services:
  app:
    restart: no
    build:
      context: .
      dockerfile: docker/nextjs/Dockerfile
      target: dev
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:3000/api/status?from=docker-compose || exit 1"
      interval: 30s
      timeout: 5s
      retries: 5
    networks:
      - carrot_market

  # caddy:
  #   image: caddy
  #   restart: no
  #   ports:
  #     - "443:443"
  #   volumes:
  #     - $PWD/docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
  #   networks:
  #     - carrot_market

  nginx:
    restart: no
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
      target: dev
    ports:
      - "443:443"
    networks:
      - carrot_market
    depends_on:
      app:
        condition: service_started
    healthcheck:
      test: ["CMD", "service nginx status"]
      interval: 30s
      timeout: 2s
      retries: 3
      start_period: 2s

networks:
  carrot_market:

